'use client';

import { useLanguage } from '@/hooks/useLanguage';
import { TRANSLATIONS } from '@/config/i18n';
import type { AnalysisResult } from '@/types';

interface ExportButtonProps {
  result: AnalysisResult;
}

export function ExportButton({ result }: ExportButtonProps) {
  const { language, t } = useLanguage();

  const handleExport = () => {
    const riskLabel = result.security.riskLabel[language];
    const qualityLabel = result.quality.qualityLabel[language];

    const lines = [
      '# ScanMyPrompt Analysis Report',
      '',
      `**Date:** ${new Date(result.timestamp).toLocaleString()}`,
      '',
      '---',
      '',
      '## Prompt',
      '',
      '```',
      result.prompt,
      '```',
      '',
      '---',
      '',
      '## Security Analysis',
      '',
      `**Risk Score:** ${result.security.riskScore}/5 (${riskLabel})`,
      '',
      `**Detections:** ${result.security.detections.length}`,
      '',
    ];

    if (result.security.detections.length > 0) {
      lines.push('### Detections', '');
      for (const det of result.security.detections) {
        lines.push(`- **${det.name[language]}** (${det.category}, severity: ${Math.round(det.severity * 100)}%)`);
        lines.push(`  - ${det.description[language]}`);
        lines.push(`  - Matched: \`${det.matchedText}\``);
        lines.push('');
      }
    }

    if (result.security.safeVersion) {
      lines.push('### Safe Version', '', '```', result.security.safeVersion, '```', '');
    }

    lines.push('---', '', '## Quality Analysis', '');
    lines.push(`**Quality Score:** ${result.quality.qualityScore}/5 (${qualityLabel})`, '');

    lines.push('### Dimensions', '');
    for (const dim of result.quality.dimensions) {
      const dimName = TRANSLATIONS.dimensions[dim.dimension as keyof typeof TRANSLATIONS.dimensions].name[language];
      lines.push(`- **${dimName}:** ${Math.round(dim.score * 100)}%`);
    }
    lines.push('');

    if (result.quality.suggestions.length > 0) {
      lines.push('### Suggestions', '');
      for (const sug of result.quality.suggestions) {
        lines.push(`- [${sug.priority.toUpperCase()}] ${sug.message[language]}`);
        lines.push(`  - Example: ${sug.example[language]}`);
        lines.push('');
      }
    }

    if (result.quality.improvedVersion !== result.prompt) {
      lines.push('### Improved Version', '', '```', result.quality.improvedVersion, '```', '');
    }

    lines.push('---', '', '*Generated by ScanMyPrompt*');

    const blob = new Blob([lines.join('\n')], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${t(TRANSLATIONS.export.filename)}-${Date.now()}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <button
      onClick={handleExport}
      className="px-4 py-2 glass glass-hover rounded-xl text-sm text-gray-500 hover:text-gray-900 transition-all flex items-center gap-2"
    >
      <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
        <path strokeLinecap="round" strokeLinejoin="round" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
      </svg>
      {t(TRANSLATIONS.export.button)}
    </button>
  );
}
